### ISSUE TITLE
自己训练出的模型直接使用会报错？

### ISSUE THREAD

**Issue by juventi** [YCG09/chinese_ocr#18]
自己训练出的模型是包括ctc和loss参数的，直接在densenet/models下使用会报错：
ValueError: Dimension 1 in both shapes must be equal, but are 5990 and 17765 for 'Assign_159' (op: 'Assign') with input shapes: [768,5990], [768,17765].

求大神指导怎么修改模型?

**Comment by YCG09** [comment]
你是用了自己的字典？

**Comment by juventi** [comment]
@YCG09 找到原因了。。
py2读取字典txt不能用coding=‘utf-8’, 读出来的字典大小有17765个...
不过这样居然训练都还可以收敛。。

**Comment by qiangqiangsir** [comment]
楼主你好！
    我换了一个训练字典，用的是常用的3755个汉字，训练样本336967，batch_size=16，修改后训练总是出现一下问题，（每次出现的训练batch还不一样）请问是什么原因呢。
Caused by op 'ctc/CTCLoss', defined at:
  File "/home/python/chinese_ocr-master/train/train.py", line 167, in <module>
    basemodel, model = get_model(img_h, nclass)
  File "/home/python/chinese_ocr-master/train/train.py", line 149, in get_model
    loss_out = Lambda(ctc_lambda_func, output_shape=(1,), name='ctc')([y_pred, labels, input_length, label_length])
  File "/usr/local/lib/python3.5/dist-packages/keras/engine/topology.py", line 619, in __call__
    output = self.call(inputs, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/keras/layers/core.py", line 685, in call
    return self.function(inputs, **arguments)
  File "/home/python/chinese_ocr-master/train/train.py", line 136, in ctc_lambda_func
    return K.ctc_batch_cost(labels, y_pred, input_length, label_length)
  File "/usr/local/lib/python3.5/dist-packages/keras/backend/tensorflow_backend.py", line 3956, in ctc_batch_cost
    sequence_length=input_length), 1)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/ctc_ops.py", line 152, in ctc_loss
    ignore_longer_outputs_than_inputs=ignore_longer_outputs_than_inputs)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/gen_ctc_ops.py", line 168, in _ctc_loss
    name=name)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/op_def_library.py", line 767, in apply_op
    op_def=op_def)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 2630, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 1204, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

InvalidArgumentError (see above for traceback): #Saw a non-null label (index >= num_classes - 1) following a null label, batch: 11 num_classes: 3755 labels: 1023,3052,2771,1578,1443
	 [[Node: ctc/CTCLoss = CTCLoss[ctc_merge_repeated=true, ignore_longer_outputs_than_inputs=false, preprocess_collapse_repeated=false, _device="/job:localhost/replica:0/task:0/cpu:0"](ctc/Log/_2477, ctc/ToInt64/_2479, ctc/ToInt32_2/_2481, ctc/ToInt32_1/_2483)]]
	 [[Node: training/Adam/gradients/ctc/CTCLoss_grad/mul/_2513 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/gpu:0", send_device="/job:localhost/replica:0/task:0/cpu:0", send_device_incarnation=1, tensor_name="edge_5065_training/Adam/gradients/ctc/CTCLoss_grad/mul", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/gpu:0"]()]]

swig/python detected a memory leak of type 'int64_t *', no destructor found.
swig/python detected a memory leak of type 'int64_t *', no destructor found.

**Comment by YCG09** [comment]
@qiangqiangsir 由于keras的backend是tensorflow，tf的CTC把最后一个字符作为blank label，具体可以看
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/util/ctc/ctc_loss_calculator.h

**Comment by YCG09** [comment]
@qiangqiangsir 多gpu训练需要改代码，tf比较麻烦，keras还容易点，网上查查帖子吧，类似这种可以参考
https://blog.csdn.net/odailidong/article/details/79332750

**Comment by qiangqiangsir** [comment]
@YCG09  楼主你好，我参考你推荐的帖子，添加了basemodel=multi_gpu_model(basemodel,gpus=8)，可以使用多显卡训练了，参考https://blog.csdn.net/leadai/article/details/79466110在预测中（model.py文件）添加了basemodel=multi_gpu_model(basemodel,gpus=8)这一句，但是在Load模型的时候出现“ValueError: You are trying to load a weight file containing 55 layers into a model with 1 layers.” 问题
”  这是因为使用的预测和训练模型不一致吗，还是我没有添加对地方？

**Comment by YCG09** [comment]
@qiangqiangsir load模型应该不需要多卡吧，预测时候用一个gpu就可以了

**Comment by qiangqiangsir** [comment]
@YCG09  更正一下，是使用model = multi_gpu_model(model, gpus=8)时，可以使用多卡训练，如果在model.py 中不添加 basemodel=multi_gpu_model(basemodel,8)，会出现You are trying to load a weight file containing 1 layers into a model with 55 layers ，添加basemodel=multi_gpu_model(basemodel,8)会出现：tensorflow/stream_executor/cuda/cuda_dnn.cc:444] could not convert BatchDescriptor {count: 0 feature_map_count: 64 spatial: 16 261  value_min: 0.000000 value_max: 0.000000 layout: BatchDepthYX} to cudnn tensor descriptor: CUDNN_STATUS_BAD_PARAM
Aborted (core dumped)

**Comment by YCG09** [comment]
@qiangqiangsir load模型不需要用multi_gpu_model，你模型保存的有问题，我没用多卡训练过，你查查keras的文档吧，google下相关问题，比如这种
https://github.com/keras-team/keras/issues/8123

**Comment by evanfly** [comment]
@qiangqiangsir 同问，在8个gpu下训练的model，在单gpu下测试，出现同样的错误，You are trying to load a weight file containing 1 layers into a model with 55 layers ，如果在加载model的时候改成basemodel.load_weights(modelPath,by_name=True)，有结果输出，但都是乱码，请问你这个问题解决了吗

**Comment by jake221** [comment]
> @qiangqiangsir 同问，在8个gpu下训练的model，在单gpu下测试，出现同样的错误，You are trying to load a weight file containing 1 layers into a model with 55 layers ，如果在加载model的时候改成basemodel.load_weights(modelPath,by_name=True)，有结果输出，但都是乱码，请问你这个问题解决了吗

这个问题是Keras版本超过2.2.0导致的。你把Keras版本降低下，然后重新训练加载这个问题就避免了。

https://github.com/tensorflow/tensorflow/issues/24623

**Comment by jake221** [comment]
> @qiangqiangsir 同问，在8个gpu下训练的model，在单gpu下测试，出现同样的错误，You are trying to load a weight file containing 1 layers into a model with 55 layers ，如果在加载model的时候改成basemodel.load_weights(modelPath,by_name=True)，有结果输出，但都是乱码，请问你这个问题解决了吗

将加载模型部分的basemodel改为model

完整代码

def get_model(img_h, nclass):
    input = Input(shape=(img_h, None, 1), name='the_input')
    y_pred = densenet.dense_cnn(input, nclass)

    basemodel = Model(inputs=input, outputs=y_pred)
    basemodel.summary()

    labels = Input(name='the_labels', shape=[None], dtype='float32')
    input_length = Input(name='input_length', shape=[1], dtype='int64')
    label_length = Input(name='label_length', shape=[1], dtype='int64')

    loss_out = Lambda(ctc_lambda_func, output_shape=(1,), name='ctc')([y_pred, labels, input_length, label_length])

    model = Model(inputs=[input, labels, input_length, label_length], outputs=loss_out)
    parrel_model = multi_gpu_model(model, gpus=2)
    parrel_model.compile(loss={'ctc': lambda y_true, y_pred: y_pred}, optimizer='adam', metrics=['accuracy'])

    return basemodel, parrel_model

K.set_session(get_session())
    reload(densenet)
    basemodel, model = get_model(img_h, nclass)

    modelPath = './models/pretrain_model/keras.h5'
    if os.path.exists(modelPath):
        print("Loading model weights...")
        model.load_weights(modelPath)
        print('done!')

**Comment by P5best** [comment]
@qiangqiangsir  我也是用了非定长数据集训练，但是需要nclass+2才能跑，不知为何，是字典和数据集有什么细节问题吗
